version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
