version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
  fail_on_warning: false

formats:
  - pdf
  - epub

conda:
  environment: docs/stc_conda.yaml

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
