version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - echo "At pre_build step, installing package locally"
      - pip install .

sphinx:
  fail_on_warning: false

formats:
  - pdf
  - epub

conda:
  environment: docs/stc_conda.yaml
