name: Lint and make TODO issues

on: [push, pull_request]

jobs:
  lint_and_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # NB removed for now due to some issues
      # - name: Install Black with jupyter functionality
      #   run: pip install black[jupyter]
      # - name: Run black
      #   run: black .
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.3
        id: todo
